# Generated by Django 4.0.3 on 2022-06-30 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('done', models.IntegerField(default=0)),
                ('image', models.URLField(blank=True, null=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('done', models.BooleanField(default=False)),
                ('repeat', models.IntegerField(default=30)),
                ('days', models.ManyToManyField(blank=True, null=True, related_name='days', to='sport.day')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.program'),
        ),
    ]
