# Generated by Django 4.0.3 on 2022-06-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='days',
            field=models.ManyToManyField(blank=True, related_name='days', to='sport.day'),
        ),
    ]
