# Generated by Django 4.0.6 on 2022-07-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_alter_exercise_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='done',
        ),
        migrations.AddField(
            model_name='day',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
