# Generated by Django 4.0.6 on 2022-07-17 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_remove_exercise_done_day_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='program',
        ),
        migrations.AddField(
            model_name='program',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.day'),
        ),
    ]
