# Generated by Django 4.0.6 on 2022-07-17 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0005_alter_program_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='days',
        ),
        migrations.RemoveField(
            model_name='program',
            name='program',
        ),
        migrations.AddField(
            model_name='day',
            name='days',
            field=models.ManyToManyField(blank=True, related_name='exercise', to='sport.exercise'),
        ),
        migrations.AddField(
            model_name='day',
            name='program',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.program'),
        ),
    ]
