# Generated by Django 4.0.6 on 2022-07-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0006_remove_exercise_days_remove_program_program_day_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='days',
            new_name='exercises',
        ),
    ]
